config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('orders.urls', namespace='orders')),
    path("api/", include('orders.urls_api', namespace='orders_api')),

]

orders/urls.py
from django.urls import path
from orders.apps import OrdersConfig
from orders.views import OrderListView, OrderDetailView, OrderCreateView, OrderUpdateView, OrderDeleteView

app_name = OrdersConfig.name

urlpatterns = [
    #  urls для заказов:
    path('', OrderListView.as_view(), name='list'),
    path('details/<int:pk>/', OrderDetailView.as_view(), name='detail'),
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='delete'),
]

orders/models.py
"""
table_number (номер стола)
items (список заказанных блюд с ценами) - ДОПОЛНИТЕЛЬНАЯ МОДЕЛЬ
total_price (общая стоимость заказа, вычисляется автоматически) - ПОПРОБУЮ РЕАЛИЗОВАТЬ ЧЕРЕЗ ГЕТТЕР
status (статус заказа: “в ожидании”, “готово”, “оплачено”)
"""
from django.db import models


class Dish(models.Model):
    """Модель блюда"""

    name = models.CharField(max_length=200, verbose_name="Название блюда")
    price = models.FloatField(verbose_name="Цена в руб.")

    class Meta:
        verbose_name = "блюдо"
        verbose_name_plural = "блюда"

    def __str__(self):
        return self.name


class Order(models.Model):
    """Модель заказа"""

    STATUS_CHOICES = (
        ("WAITING", "В ожидании"),
        ("READY", "Готово"),
        ("PAID", "Оплачено"),
    )

    table_number = models.PositiveIntegerField(verbose_name="Номер стола")
    status = models.CharField(
        default='WAITING',
        max_length=150,
        verbose_name="Статус заказа",
        choices=STATUS_CHOICES,
        blank=True,
        null=True,
    )
    items = models.ManyToManyField(
        Dish,
        verbose_name="список блюд",
        related_name="orders",
        help_text="необходимо выбрать хотя бы одно блюдо из списка доступных",
    )

    @property
    def total_price(self):
        """Возвращаем полный прайс выбранных блюд"""

        total_price = sum(item.price for item in self.items.all())

        return total_price

    class Meta:
        verbose_name = "заказ"
        verbose_name_plural = "заказы"

orders/forms.py
from django.forms import ModelForm, BooleanField
from orders.models import Order


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class OrderCreateForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Order
        fields = ('table_number', 'items',)


class OrderUpdateForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Order
        fields = ('table_number', 'items', 'status',)

orders/views.py
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from orders.forms import OrderCreateForm, OrderUpdateForm
from orders.models import Order


class OrderListView(ListView):
    """Отображение списка заказов"""

    model = Order

    def get_context_data(self, *, object_list=None, **kwargs):
        """Подстчет выручки за все заказы со статусом PAID"""

        context_data = super().get_context_data(**kwargs)
        proceeds: float = 0
        for order in Order.objects.all():
            if order.status == 'PAID':
                proceeds += order.total_price

        context_data['proceeds'] = proceeds

        return context_data

    def get_queryset(self):
        """Реализация поиска заказа"""
        queryset = super().get_queryset()

        # ПОИСК ПО НОМЕРУ СТОЛА ИЛИ ПО СТАТУСУ ЗАКАЗА:
        search = self.request.GET.get("search", "")
        if search.isdigit():
            queryset = queryset.filter(Q(table_number=search))
            return queryset
        elif search:
            # ВНИМАНИЕ! Если поиск идет по статусу заказа, то вводить статус необходимо так:
            # WAITING, PAID или READY
            queryset = queryset.filter(Q(status=search))
            return queryset
        else:
            return queryset


class OrderDetailView(DetailView):
    """Детальный просмотр заказа"""

    model = Order

    def get_context_data(self, **kwargs):
        """Вынести в контекст блюда из заказа в отдельную переменную"""

        context_data = super().get_context_data(**kwargs)
        dishes = [item.name for item in Order.objects.get(pk=self.kwargs['pk']).items.all()]
        context_data['dishes'] = dishes

        return context_data


class OrderCreateView(CreateView):
    """Создание заказа"""

    model = Order
    form_class = OrderCreateForm
    success_url = reverse_lazy('orders:list')


class OrderUpdateView(UpdateView):
    model = Order
    form_class = OrderUpdateForm
    success_url = reverse_lazy('orders:list')


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:list')

orders/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="/docs/5.3/assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'orders/includes/inc_menu.html' %}
</header>

<main>


    {% block content %}
    {% endblock %}

</main>


<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

orders/templates/orders/includes/inc_menu.html
 <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>Навигационная панель</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'orders:list' %}" class="text-white">К списку заказов</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                 stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                 viewBox="0 0 24 24">
                <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                <circle cx="12" cy="13" r="4"/>
            </svg>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>

orders/templates/orders/order_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="row text-center">
    <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Удалить заказ?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a href="{% url 'orders:list' %}" class="btn btn-secondary">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col-lg-9 col-md-6 col-sm-12 mx-auto">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Номер заказа: {{ object.pk}}</p>
                        <p class="card-text">Номер стола: {{ object.table_number }}</p>
                        <p class="card-text">Сумма заказа: {{ object.total_price }}</p>
                        <p class="card-text">Статус: {{object.status}}</p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-dark" href="{% url 'orders:list' %}" role="button">Вернуться к списку
                                    заказов</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer text-center">
                        <h3>Блюда:</h3>

                        {% for dish in dishes %}
                        <h4>{{dish}}</h4>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

orders/templates/orders/order_form.html
{% extends 'base.html' %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if object %}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    {% else %}
                    <button type="submit" class="btn btn-success">Создать</button>
                    {% endif %}
                    <div class="btn-group">
                        <a class="btn btn-danger " href="{% url 'orders:list' %}" role="button">Отмена</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

orders/templates/orders/order_list.html
{% extends 'base.html' %}
{% block content %}

<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <a href="{% url 'orders:create' %}" class="btn btn-info my-2">Добавить заказ</a>
            <button class="btn btn-secondary" type="button" data-bs-toggle="collapse"
                    data-bs-target="#multiCollapseExample2" aria-expanded="false"
                    aria-controls="multiCollapseExample2">Расчет выручки
            </button>
            <div class="row">
                <div class="col">
                    <div class="collapse multi-collapse" id="multiCollapseExample2">
                        <div class="card card-body">
                            Полная выручка за все заказы составляет: {{proceeds}} руб.
                        </div>
                    </div>
                </div>
            </div>
            </p>
        </div>
    </div>
    <div class="col-3 text-center mx-auto">
        <form class="d-flex" action="{% url 'orders:list' %}">
            <input class="form-control me-2" type="search" placeholder="Введите номер стола" aria-label="Поиск"
                   name="search">
            <button class="btn btn-black" type="submit">Поиск</button>
        </form>
    </div>
</section>

<table class="table mt-3 text-center">
    <thead>
    <tr>
        <th scope="col">Номер заказа</th>
        <th scope="col">Номер стола</th>
        <th scope="col">Общая стоимость</th>
        <th scope="col">Статус</th>
    </tr>
    </thead>
    <tbody>
    {% for order in order_list %}
    {% if order.status == 'PAID' %}
    <tr class="table-success">
        {% elif order.status == 'WAITING' %}
    <tr class="table-danger">
        {% else %}
    <tr class="table-warning">
        {% endif %}
        <td>{{order.pk}}</td>
        <td>{{order.table_number}}</td>
        <td>{{order.total_price}} руб.</td>
        <td>{{order.status}}</td>
        <td><a class="btn btn-dark rounded-pill" href="{% url 'orders:detail' order.pk %}"
               role="button">Перейти к заказу</a></td>
        <td><a class="btn btn-dark mx-1 rounded-pill" href="{% url 'orders:update' order.pk %}"
               role="button">Внести изменения</a></td>
        <td><a class="btn btn-danger mx-1 rounded-pill" href="{% url 'orders:delete' order.pk %}"
               role="button">Удалить заказ</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}